title: アラフィフ親父とアラサーミセスの挑戦
description: AI・副業・悩み・ギャップ・そして日々の奮闘。誰かの何かの参考になれば。
baseurl: "/reo"

# ★★★ ここからが、新しいコレクションの設定です！ ★★★
collections:
  our_story:
    output: true
    permalink: /story/:path/
  logs:
    output: true
    permalink: /logs/:path/
  tweets:
    output: true
    permalink: /tweets/:path/