title: アラフィフ親父とアラサーミセスの挑戦
description: AI・副業・悩み・ギャップ・そして日々の奮闘。誰かの何かの参考になれば。
baseurl: "/reo"

collections:
  our_story:
    output: true
    permalink: /story/:name/
  logs:
    output: true
    permalink: /logs/:name/
  tweets:
    output: true
    permalink: /tweets/:name/